### ISSUE TITLE
windows上怎么用？

### ISSUE THREAD

**Issue by VacantHusky** [luguocfw/WaveChannel#2]
我用vs2019打开wave_trans.sln，我也不懂怎么用vs，最后生成了Release\lib\librs.lib。
但是我不知道怎么用这个lib。

能否生成一个exe？即使没有UI界面也可以用命令的方式调用，或者dll这种。

**Comment by VacantHusky** [comment]
已经编译好了。

**Comment by luguocfw** [comment]
vs工程里有两个应用项目:wave_tran_recv和wave_tran_send，可以用来测试，不过它是写入到音频文件和读取音频文件来测试的，没有直接调用音频设备。
主要是windows上之前直接调用音频设备测试效果不是很好，而且这个东西也很少用在windows上，所以比较直观的demo就是android的。
















在 2024-01-10 13:00:48，"tiger-wang" ***@***.***> 写道：

我用vs2019打开wave_trans.sln，我也不懂怎么用vs，最后生成了Release\lib\librs.lib。
但是我不知道怎么用这个lib。

能否生成一个exe？即使没有UI界面也可以用命令的方式调用，或者dll这种。
